# Generated by Django 3.1.4 on 2020-12-23 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('text', models.TextField(verbose_name='本文')),
                ('description', models.TextField(blank=True, verbose_name='概要')),
                ('image', models.ImageField(upload_to='', verbose_name='サムネイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
